version: 2
jobs:
  bobby:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "doubletrouble"
  sally:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "doubletrouble"
workflows:
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sally